apiVersion: hy548.csd.uoc.gr/v1
kind: Fruit
metadata:
  name: apple
spec:
  origin: Krousonas
  count: 3
  grams: 900 
---
apiVersion: hy548.csd.uoc.gr/v1
kind: Fruit
metadata:
  name: cherry
spec:
  origin: Krousonas
  count: 4
  grams: 80 
---
apiVersion: hy548.csd.uoc.gr/v1
kind: Fruit
metadata:
  name: orange
spec:
  origin: Krousonas
  count: 3
  grams: 1000